# Generated by Django 4.1 on 2023-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills_employee_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('employment_status', models.CharField(max_length=40)),
                ('no_of_kids', models.IntegerField(null=True)),
            ],
        ),
    ]
